version: "3"

services:
  redis:
    container_name: redis
    image: redis:7.0
    volumes:
      - ./data/redis-single/local:/data
    ports:
      - "6379:6379"
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
