apiVersion: v1
kind: Namespace
metadata:
  name: feature-store-portal
---
apiVersion: v1
kind: Service
metadata:
  name: feature-store
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: feature-store
  type: LoadBalancer
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: feature-store
spec:
  replicas: 3
  selector:
    matchLabels:
      app: feature-store
  template:
    metadata:
      labels:
        app: feature-store
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: feast-gcp-gke-node-pool
      restartPolicy: Always
      containers:
        - name: feature-store
          image: asia.gcr.io/feast-gcp-project-id/feast-gcp:0.1.0
          imagePullPolicy: Always
          ports:
          - containerPort: 80
          env:
          - name: ENV
            value: prod
